# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - "386"
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/cloudspannerecosystem/wrench/cmd.version={{.Version}}
    ignore:
      - goos: darwin
        goarch: 386

archives:
  - format: tar.gz
    name_template: '{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    format_overrides:
    - goos: windows
      format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

# https://goreleaser.com/customization/docker/
dockers:
- image_templates: ["ghcr.io/cloudspannerecosystem/{{ .ProjectName }}:{{ .Version }}-amd64"]
  goarch: amd64
  dockerfile: Dockerfile
  use: buildx
  build_flag_templates:
  - --platform=linux/amd64
- image_templates: ["ghcr.io/cloudspannerecosystem/{{ .ProjectName }}:{{ .Version }}-arm64v8"]
  goarch: arm64
  dockerfile: Dockerfile
  use: buildx
  build_flag_templates:
  - --platform=linux/arm64/v8
docker_manifests:
- name_template: ghcr.io/cloudspannerecosystem/{{ .ProjectName }}:{{ .Version }}
  image_templates:
  - ghcr.io/cloudspannerecosystem/{{ .ProjectName }}:{{ .Version }}-amd64
  - ghcr.io/cloudspannerecosystem/{{ .ProjectName }}:{{ .Version }}-arm64v8
- name_template: ghcr.io/cloudspannerecosystem/{{ .ProjectName }}:latest
  image_templates:
  - ghcr.io/cloudspannerecosystem/{{ .ProjectName }}:{{ .Version }}-amd64
  - ghcr.io/cloudspannerecosystem/{{ .ProjectName }}:{{ .Version }}-arm64v8
